import type { Metadata } from "next";
import Provider from "./Provider";
import Header from "./components/Header/Header";
import Footer from "./components/footer/Footer";
import "./globals.css";
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <Provider>
          <Header />
          <div className="min-h-[70vh]">
            {children}
          </div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}

